version: "2"
linters:
  enable:
    - gocritic
    - lll
  settings:
    gocritic:
      enabled-tags:
        - performance
        - style
        - experimental
      settings:
        hugeParam:
          sizeThreshold: 128
    lll:
      line-length: 80
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - lll
        path: _test\.go
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
