name: container

on:
  push:
    branches:
      - container

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - uses: docker/build-push-action@v2
