name: Deploy Reverse Hash Service to AWS ECR

on:
  push:
    branches:
      - main
env:
  AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
  ECR_REPOSITORY: reverse_hash_service

jobs:
  deploy:
    environment:
      name: ${{ github.ref_name }}
    name: Build and Deploy RHS service to AWS
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
      packages: read
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: docker/setup-qemu-action@v1

      - uses: docker/setup-buildx-action@v1

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        env:
          AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
          AWS_ROLE_TO_ASSUME: ${{ secrets.AWS_ROLE_TO_ASSUME }}
        with:
          aws-region: ${{ env.AWS_DEFAULT_REGION }}
          role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT_ID }}:role/${{ env.AWS_ROLE_TO_ASSUME }}
          role-session-name: GitHubActionsSession

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1
        id: login-ecr

      - name: Get version
        run: echo "::set-output name=VERSION::$(git rev-parse --short HEAD)"
        id: version
        
      - name: Build and push
        uses: docker/build-push-action@v5
        env:
          IMAGE_TAG: ${{ steps.version.outputs.VERSION }}
        with:
          context: ./
          file: ./Dockerfile
          push: false
          tags: iden3/reverse-hash-service:${{ env.IMAGE_TAG }}
          platforms: linux/amd64
          outputs: type=docker

      - name: Tag and push image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ env.ECR_REPOSITORY }}
          IMAGE_TAG: ${{ steps.version.outputs.VERSION }}
        run: |
          docker tag iden3/reverse-hash-service:${{ env.IMAGE_TAG }} ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}
          docker push ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}

          docker tag iden3/reverse-hash-service:${{ env.IMAGE_TAG }} ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:latest
          docker push ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:latest
