name: Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    strategy:
      matrix:
        containers:
        - 1.22.12-bookworm
        - 1.23.9-bookworm
        - 1.24.3-bookworm
    runs-on: ubuntu-latest
    container: golang:${{ matrix.containers }}
    env:
      PGPASSWORD: pgpwd
      PGHOST: postgres
      PGUSER: postgres
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            /go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Unit Tests
        run: go test -v -race -timeout=60s ./...
    services:
      postgres:
        image: postgres:14.2
        env:
          POSTGRES_PASSWORD: pgpwd
